site_name: uArm Docs
pages:
    - Home: index.md
    - Getting Started: getting_started.md
    - uArm CommandLine Tools:   uarm_cli.md
theme: flatly
markdown_extensions:
    - markdown_include.include
